// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PlantUMLEditor
{
    internal sealed partial class Vsix
    {
        public const string Id = "PlantUML Viewer.552842d3-53f3-4aec-b8c1-7731c4e405a6";
        public const string Name = "PlantUML Editor";
        public const string Description = @"PlantUML Editor";
        public const string Language = "en-US";
        public const string Version = "1.1.131";
        public const string Author = "Vincent Dagpin";
        public const string Tags = "PlantUML";
    }
}
